
workflows:
  android-build:
    name: Android Release Build (AAB)
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
        - signing
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env
      - name: Build web assets
        script: npm run build
      - name: Recreate and Sync Android Platform
        script: |
          # 1. Clean Slate: Remove any old android directory to prevent conflicts.
          rm -rf android
          
          # 2. Add Platform: Creates the native Android project structure.
          npx cap add android
          
          # 3. Sync Platform: This is the crucial step. It copies web assets
          #    and creates Capacitor's config files (like capacitor.settings.gradle) in the native project.
          npx cap sync android
      - name: Update Version Code and Name
        script: |
          # Extract version info from sw.js
          VERSION_LINE=$(grep "AppVersion:" public/sw.js)
          if [ -z "$VERSION_LINE" ]; then
            echo "Error: Could not find 'AppVersion:' line in public/sw.js"
            exit 1
          fi
          
          VERSION_NAME=$(echo "$VERSION_LINE" | sed -n 's/.*AppVersion: \([^ ]*\) .*/\1/p')
          VERSION_CODE=$(echo "$VERSION_LINE" | sed -n 's/.*(\(.*\)).*/\1/p')
          
          if [ -z "$VERSION_NAME" ] || [ -z "$VERSION_CODE" ]; then
            echo "Error: Could not extract version from public/sw.js. Line was: $VERSION_LINE"
            exit 1
          fi

          echo "Using Version Name: $VERSION_NAME from sw.js"
          echo "Using Version Code: $VERSION_CODE from sw.js"

          # Update build.gradle
          sed -i.bak "s/versionCode 1/versionCode $VERSION_CODE/" android/app/build.gradle
          sed -i.bak "s/versionName \"1.0\"/versionName \"$VERSION_NAME\"/" android/app/build.gradle
      - name: Decode Keystore File
        script: echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
      - name: Make gradlew executable
        script: chmod +x android/gradlew
      - name: Build Android Release AAB
        script: |
          cd android && ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_BUILD_DIR/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_ALIAS_PASSWORD
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
