
workflows:
  android-build:
    name: Android Build
    environment:
      # Build အတွက် လိုအပ်သော နည်းပညာများ သတ်မှတ်ခြင်း
      node: 20 # Node.js version
      java: 21 # Java version (Android Build အတွက် လိုအပ်)
      groups:
        - supabase_keys # Supabase key တွေအတွက် group
      
    scripts:
      - name: Install dependencies
        # package.json ထဲက dependencies များကို download လုပ်ခြင်း
        script: npm install
        
      - name: Create .env file
        # Codemagic ကနေရလာတဲ့ key တွေကို .env file ထဲကို ရေးထည့်ခြင်း
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env

      - name: Build Web Assets
        # Web Code (Next.js/React) များကို Production အတွက် Build လုပ်ခြင်း
        script: npm run build
      
      - name: Create out directory
        # Capacitor sync အတွက် လိုအပ်သော out folder ကို ကြိုတင်ဖန်တီးခြင်း
        script: mkdir -p out
        
      - name: Add Android Platform
        # Capacitor အတွက် Android platform ကို ထည့်သွင်းခြင်း
        script: npx cap add android

      - name: Sync Capacitor project
        # Build ပြီးသား Web Code များကို Android Native Project ထဲသို့ ကူးထည့်ခြင်း
        script: npx cap sync android
        
      - name: Build Android Release APK
        # Android folder ထဲသို့ ဝင်၍ APK ဖိုင်ကို တကယ်တမ်း ထုတ်လုပ်ခြင်း
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      # ထုတ်ပြီးသား APK ဖိုင်ကို Codemagic Dashboard မှာ မြင်ရအောင် ညွှန်းဆိုခြင်း
      - android/app/build/outputs/**/*.apk
