
workflows:
  android-build:
    name: Android Build
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
      
    scripts:
      - name: Install dependencies
        script: npm install
        
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env

      - name: Build Web Assets
        script: npm run build
      
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
