
workflows:
  android-build:
    name: Android Build
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
        - signing
      
    scripts:
      - name: Install dependencies
        script: npm install
        
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env

      - name: Build Web Assets
        script: npm run build
      
      - name: Add and Sync Android Platform
        script: |
          npx cap add android
          npx cap sync android
          
      - name: Build Android Release APK
        script: |
          cd android
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
