
workflows:
  android-build:
    name: Android Release Build (AAB)
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
        - signing
        -VERSION_CODE
        -VERSION_NAME
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env
      - name: Build web assets
        script: npm run build
      - name: Recreate and Sync Android Platform
        script: |
          # 1. Clean Slate: Remove any old android directory to prevent conflicts.
          rm -rf android
          
          # 2. Add Platform: Creates the native Android project structure.
          npx cap add android
          
          # 3. Sync Platform: This is the crucial step. It copies web assets (from the 'out' dir)
          #    and creates Capacitor's config files (like capacitor.settings.gradle) in the native project.
          npx cap sync android
      - name: Decode Keystore File
        script: echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
      - name: Make gradlew executable
        script: chmod +x android/gradlew
      - name: Build Android Release AAB
        script: |
          cd android && ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_BUILD_DIR/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_ALIAS_PASSWORD
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
