
workflows:
  android-build:
    name: Android Release Build
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
        - signing
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env
      - name: Build web assets
        script: npm run build
      - name: Create out directory for Capacitor
        script: mkdir -p out
      - name: Add Android Platform
        script: |
          rm -rf ./android
          npx cap add android
      - name: Sync Capacitor Project
        script: npx cap sync android
      - name: Decode Keystore File
        script: echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
      - name: Create 'gradle.properties' for Signing
        script: |
          PROPERTIES_PATH="android/gradle.properties"
          echo "MY_RELEASE_KEYSTORE_FILE=$CM_BUILD_DIR/keystore.jks" >> $PROPERTIES_PATH
          echo "MY_RELEASE_KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD" >> $PROPERTIES_PATH
          echo "MY_RELEASE_KEY_ALIAS=$CM_KEY_ALIAS" >> $PROPERTIES_PATH
          echo "MY_RELEASE_KEY_PASSWORD=$CM_KEY_ALIAS_PASSWORD" >> $PROPERTIES_PATH
      - name: Add Signing Config to build.gradle
        script: |
          BUILD_GRADLE_PATH="android/app/build.gradle"
          SIGNING_CONFIG="
              android {
                  signingConfigs {
                      release {
                          if (project.hasProperty('MY_RELEASE_KEYSTORE_FILE')) {
                              storeFile file(MY_RELEASE_KEYSTORE_FILE)
                              storePassword MY_RELEASE_KEYSTORE_PASSWORD
                              keyAlias MY_RELEASE_KEY_ALIAS
                              keyPassword MY_RELEASE_KEY_PASSWORD
                          }
                      }
                  }
                  buildTypes {
                      release {
                          signingConfig signingConfigs.release
                      }
                  }
              }
          "
          echo "$SIGNING_CONFIG" >> $BUILD_GRADLE_PATH
      - name: Build Android Release AAB
        script: |
          cd android && ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/app-release.aab

