
workflows:
  android-build:
    name: Android Release Build (AAB)
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
        - signing
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env
      - name: Build web assets
        script: npm run build
      - name: Recreate Android Platform
        script: |
          # Force a clean slate to ensure a predictable environment.
          rm -rf android
          npx cap add android
      - name: Update Version Code and Name
        script: |
          # Use the build number as the version code. This is crucial as the project is recreated.
          sed -i.bak "s/versionCode 1/versionCode $BUILD_NUMBER/" android/app/build.gradle
          # Create a human-readable version name from the build number
          VERSION_NAME=$(echo "1.0.$BUILD_NUMBER" | cut -d'.' -f1-3)
          sed -i.bak "s/versionName \"1.0\"/versionName \"$VERSION_NAME\"/" android/app/build.gradle
      - name: Decode Keystore File
        script: echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
      - name: Make gradlew executable
        script: chmod +x android/gradlew
      - name: Build Android Release AAB
        script: |
          cd android && ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_BUILD_DIR/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_ALIAS_PASSWORD
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
