
workflows:
  android-build:
    name: Android Release Build (AAB)
    environment:
      node: 20
      java: 21
      groups:
        - supabase_keys
        - signing
        - VERSION_CODE
        - VERSION_NAME
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Create .env file
        script: |
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY" >> .env
      - name: Build and Export web assets
        script: npm run export
      - name: Recreate Android Platform and Sync
        script: |
          # 1. Clean Slate: Remove any old android directory to prevent conflicts.
          rm -rf android
          
          # 2. Add Platform: Creates the native Android project structure.
          npx cap add android
          
          # 3. Copy web assets and config files.
          npx cap copy android

          # 4. Update native plugins
          npx cap update android
      - name: Set Android Version
        script: |
          # This script injects the version code and name from Codemagic environment variables
          # into the Android project's build.gradle file. It runs after 'cap sync' to avoid being overwritten.
          echo "Setting Android version in build.gradle..."
          awk -v new_code="$VERSION_CODE" '/versionCode/ { $2 = new_code } 1' android/app/build.gradle > android/app/build.gradle.tmp && mv android/app/build.gradle.tmp android/app/build.gradle
          awk -v new_name="$VERSION_NAME" '/versionName/ { $2 = "\"" new_name "\"" } 1' android/app/build.gradle > android/app/build.gradle.tmp && mv android/app/build.gradle.tmp android/app/build.gradle
          echo "Successfully updated android/app/build.gradle with:"
          grep "versionCode\|versionName" android/app/build.gradle
      - name: Decode Keystore File
        script: echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
      - name: Make gradlew executable
        script: chmod +x android/gradlew
      - name: Build Android Release AAB
        script: |
          cd android && ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_BUILD_DIR/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_ALIAS_PASSWORD
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab


