
-- Step 1: Drop the old trigger and function to avoid conflicts during schema changes.
DROP TRIGGER IF EXISTS on_new_comment_send_notification ON public.post_comments;
DROP FUNCTION IF EXISTS public.send_comment_notification();

-- Step 2: Drop the old notifications table which has the incorrect schema.
DROP TABLE IF EXISTS public.notifications;

-- Step 3: Create the new 'notifications' table with the correct columns and data types.
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id UUID NOT NULL,
    actor_id UUID NOT NULL,
    type TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    target_post_id BIGINT, -- This is the correct column for storing Post IDs.
    target_id TEXT, -- Kept for other notification types if needed, but will NOT be used for comments.
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Foreign key constraints to ensure data integrity
    CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
    CONSTRAINT notifications_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
    CONSTRAINT notifications_target_post_id_fkey FOREIGN KEY (target_post_id) REFERENCES public.posts(id) ON DELETE CASCADE
);

-- Add comments for clarity
COMMENT ON TABLE public.notifications IS 'Stores notifications for users (e.g., new comments, new followers).';
COMMENT ON COLUMN public.notifications.type IS 'Type of notification (e.g., new_comment, new_follower)';
COMMENT ON COLUMN public.notifications.target_post_id IS 'Stores the ID of the related post for comment notifications.';


-- Step 4: Recreate the database function to use the new 'target_post_id' column.
CREATE OR REPLACE FUNCTION public.send_comment_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  post_owner_id UUID;
BEGIN
  -- Get the owner of the post that was commented on
  SELECT user_id INTO post_owner_id
  FROM public.posts
  WHERE id = NEW.post_id;

  -- Only send a notification if the commenter is not the post owner
  IF NEW.user_id <> post_owner_id THEN
    -- Correctly insert the post_id into the 'target_post_id' column.
    INSERT INTO public.notifications (recipient_id, actor_id, type, target_post_id)
    VALUES (post_owner_id, NEW.user_id, 'new_comment', NEW.post_id);
  END IF;

  RETURN NEW;
END;
$$;

-- Step 5: Recreate the trigger to call the updated function.
CREATE TRIGGER on_new_comment_send_notification
  AFTER INSERT ON public.post_comments
  FOR EACH ROW
  EXECUTE FUNCTION public.send_comment_notification();
